---
- hosts: localhost
  connection: local
  tasks:
  - name: find local ssh keys
    find: path='./' patterns='id_rsa.*'
    register: ssh_found
  - name: create ssh key
    command: ssh-keygen -t rsa -N '' -f id_rsa
    delegate_to: localhost
    ignore_errors: yes
    when: ssh_found.matched == 0

- hosts: all
  become: true
  become_user: root
  tasks:
  - name: create and update ssh for shared communications
    include: tasks/ssh.yml
  - name: ensure hosts file is correct
    include: tasks/hosts.yml
  - name: ensure resolve has search for domain
    include: tasks/resolve.yml
  - name: upload files
    copy: src={{item}} dest=/root/{{item}} mode=0755
    with_items:
      - add_flavor.sh
      - post-install.sh
      - setup_network.sh
      - import_image.sh
      - node_delete.sh
      - tmp_swift.sh
      - launch.sh
  - name: upload multinode template
    template: src=templates/multinode.j2 dest=/root/multinode

  - name: include deployment for debian hosts
    include: debian.yml

- hosts: control
  become: true
  become_user: root
  tasks:
  - name: configure local storage for swift
    command: /root/tmp_swift.sh
  - name: launch openstack with kolla
    command: kolla-ansible -i multinode deploy
    register: deploy_multinode
    ignore_errors: true
  - name: run post-install config
    command: ./post-install.sh
    register: post_install
    when: deploy_multinode.rc == 0
    ignore_errors: true
  - name: enable masquerade (NAT) on external interface
    include: tasks/masq.yml
